# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tanglegence
email: info@tanglegence.com
description: Untangling Complexity
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://tanglegence.com" # the base hostname & protocol for your site

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
social:
    facebook: tanglegence
    github: tanglegence
    instagram: tanglegence
    linkedin: tanglegence
    twitter: tanglegence

# Mailchimp
mailchimp-list: https://tanglegence.us17.list-manage.com/subscribe/post?u=31c5ea412bea1f72ace39eedf&amp;id=d01aad5b5c

# Build settings
markdown: kramdown
